version: '3.7'

services: 
  backend-app:
    container_name: backend 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # This means that changes to the node_modules directory in the container will not be reflected on the host, and vice versa.
    command: npm run start
    environment:
      - PORT=${PORT}

